---
name: Conformance

on:
  pull_request_target:

jobs:
  conformance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: setup tflint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.34.1

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29

      - name: pre-commit
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: "--show-diff-on-failure --color=always --all-files  \
                       --source ${{ github.event.pull_request.base.sha }} \
                       --origin ${{ github.event.pull_request.head.sha }}"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Conform
        uses: talos-systems/conform@master
        with:
          args: enforce --commit-ref=refs/remotes/origin/main
